package compiler

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ppanda/chitragupta/pkg/primitives"
)

// Target represents compilation target
type Target string

const (
	TargetCopilot Target = "copilot"
	TargetClaude  Target = "claude"
	TargetCursor  Target = "cursor"
)

// Compiler compiles primitives to target format
type Compiler struct {
	target Target
}

// New creates compiler for target
func New(target Target) *Compiler {
	return &Compiler{target: target}
}

// Compile compiles primitives to target output
func (c *Compiler) Compile(pkgPath string, outputPath string) error {
	// Discover primitives from both global and repo
	ps := &primitives.PrimitiveSet{}

	// Scan repo (.claude)
	if repoPS, err := primitives.Discover(pkgPath, "local"); err == nil {
		for _, p := range repoPS.All() {
			ps.Add(p)
		}
	}

	// Scan global (~/.claude)
	home, _ := os.UserHomeDir()
	globalPath := filepath.Join(home, ".claude")
	if globalPS, err := primitives.Discover(globalPath, "global"); err == nil {
		for _, p := range globalPS.All() {
			ps.Add(p)
		}
	}

	switch c.target {
	case TargetCopilot:
		return c.compileCopilot(ps, outputPath)
	case TargetClaude:
		return c.compileClaude(ps, outputPath)
	case TargetCursor:
		return c.compileCursor(ps, outputPath)
	default:
		return fmt.Errorf("unsupported target: %s", c.target)
	}
}

// compileCopilot generates .github/copilot-instructions.md
func (c *Compiler) compileCopilot(ps *primitives.PrimitiveSet, outputPath string) error {
	var sb strings.Builder

	sb.WriteString("# GitHub Copilot Instructions\n\n")
	sb.WriteString("Generated by Chitragupta\n\n")

	// Instructions
	if len(ps.Instructions) > 0 {
		sb.WriteString("## Instructions\n\n")
		for _, inst := range ps.Instructions {
			sb.WriteString(inst.Content)
			sb.WriteString("\n\n")
		}
	}

	// Skills
	if len(ps.Skills) > 0 {
		sb.WriteString("## Skills\n\n")
		for _, skill := range ps.Skills {
			sb.WriteString(fmt.Sprintf("### %s\n\n", skill.Name))
			sb.WriteString(skill.Content)
			sb.WriteString("\n\n")
		}
	}

	// Prompts
	if len(ps.Prompts) > 0 {
		sb.WriteString("## Prompts\n\n")
		for _, prompt := range ps.Prompts {
			sb.WriteString(fmt.Sprintf("### %s\n\n", prompt.Name))
			sb.WriteString(prompt.Content)
			sb.WriteString("\n\n")
		}
	}

	// Write to .github/copilot-instructions.md
	outputFile := filepath.Join(outputPath, ".github", "copilot-instructions.md")
	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		return err
	}

	return os.WriteFile(outputFile, []byte(sb.String()), 0644)
}

// compileClaude generates .claude/ directory structure
func (c *Compiler) compileClaude(ps *primitives.PrimitiveSet, outputPath string) error {
	claudeDir := filepath.Join(outputPath, ".claude")

	// Skills
	if len(ps.Skills) > 0 {
		skillsDir := filepath.Join(claudeDir, "skills")
		if err := os.MkdirAll(skillsDir, 0755); err != nil {
			return err
		}

		for _, skill := range ps.Skills {
			skillFile := filepath.Join(skillsDir, skill.Name+".md")
			if err := os.WriteFile(skillFile, []byte(skill.Content), 0644); err != nil {
				return err
			}
		}
	}

	// Instructions
	if len(ps.Instructions) > 0 {
		var sb strings.Builder
		for _, inst := range ps.Instructions {
			sb.WriteString(inst.Content)
			sb.WriteString("\n\n")
		}

		instructionsFile := filepath.Join(claudeDir, "CLAUDE.md")
		if err := os.WriteFile(instructionsFile, []byte(sb.String()), 0644); err != nil {
			return err
		}
	}

	// Hooks
	if len(ps.Hooks) > 0 {
		hooksDir := filepath.Join(claudeDir, "hooks")
		if err := os.MkdirAll(hooksDir, 0755); err != nil {
			return err
		}

		for _, hook := range ps.Hooks {
			hookFile := filepath.Join(hooksDir, hook.Name+".sh")
			if err := os.WriteFile(hookFile, []byte(hook.Content), 0755); err != nil {
				return err
			}
		}
	}

	return nil
}

// compileCursor generates .cursorrules
func (c *Compiler) compileCursor(ps *primitives.PrimitiveSet, outputPath string) error {
	var sb strings.Builder

	sb.WriteString("# Cursor Rules\n\n")
	sb.WriteString("Generated by Chitragupta\n\n")

	// Instructions
	if len(ps.Instructions) > 0 {
		for _, inst := range ps.Instructions {
			sb.WriteString(inst.Content)
			sb.WriteString("\n\n")
		}
	}

	// Skills
	if len(ps.Skills) > 0 {
		sb.WriteString("## Available Skills\n\n")
		for _, skill := range ps.Skills {
			sb.WriteString(fmt.Sprintf("### %s\n\n", skill.Name))
			sb.WriteString(skill.Content)
			sb.WriteString("\n\n")
		}
	}

	outputFile := filepath.Join(outputPath, ".cursorrules")
	return os.WriteFile(outputFile, []byte(sb.String()), 0644)
}
